!!! Base displacement
!!! +++---

/solu
antype,0
prefix='BaseDisp1'

time,1
nlgeom,on
sstif,on

!!! ------------------Add loads------------------------
esel,all
acel,,9.8,,

/input, '1_base_displacement', 'mac', 'C:\Users\xuhui\Desktop\JiashaoBridge\model\LoadFiles'

allsel,all
solve

!!! ------------------Export results-------------------
/input, 'output_images', 'mac', 'C:\Users\xuhui\Desktop\JiashaoBridge\model'