!!! Traffic load

/solu
antype,0
prefix='TrafficAsync'

time,1
nlgeom,on
sstif,on

!!! ------------------Add loads------------------------
esel,all
acel,,9.8,,

/input, '8_traffic_load_async', 'mac', 'C:\Users\xuchi\Desktop\JiashaoBridge\model\LoadFiles'

allsel,all
solve

!!! ------------------Export results-------------------
/input, 'output_images', 'mac', 'C:\Users\xuchi\Desktop\JiashaoBridge\model'