!!! Traffic traverse wind load

/solu
antype,0
prefix='TraffTvsWind'

time,1
nlgeom,on
sstif,on

!!! ------------------Add loads------------------------
esel,all
acel,,9.8,,

/input, '6_traffic_traverse_wind_load', 'mac', 'C:\Users\xuchi\Desktop\JiashaoBridge\model\LoadFiles'

/psf,pres,norm,1            !!! Display loads

allsel,all
esel,all
eplot
solve

!!! ------------------Export results-------------------
/input, 'output_images', 'mac', 'C:\Users\xuchi\Desktop\JiashaoBridge\model'