!!! Ultimate traverse wind load

/solu
antype,0
prefix='UltTvsWind'

time,1
nlgeom,on
sstif,on

!!! ------------------Add loads------------------------
esel,all
acel,,9.8,,

/input, '7_ultimate_traverse_wind_load', 'mac', 'C:\Users\xuhui\Desktop\JiashaoBridge\model\LoadFiles'

/psf,pres,norm,1            !!! Display loads

allsel,all
esel,all
eplot
solve
 
!!! ------------------Export results-------------------
/input, 'output_images', 'mac', 'C:\Users\xuhui\Desktop\JiashaoBridge\model'