!!! Load condition 4
!!! Dead load + ultimate_wind 

/solu
antype,0
prefix='Cnd4'

time,1
nlgeom,on
sstif,on
esel,all

!!! ------------------Add loads------------------------
!!! Dead load 
acel,,9.8,,

!!! Ultimate wind
/input, '7_ultimate_traverse_wind_load', 'mac', 'C:\Users\xuhui\Desktop\JiashaoBridge\model\LoadFiles'

eplot
allsel,all
solve

!!! ------------------Export results-------------------
/input, 'output_images', 'mac', 'C:\Users\xuhui\Desktop\JiashaoBridge\model'